"""pilot data audit and import protocol

Revision ID: 44b9875a2233
Revises: b89c8ebf3c3e
Create Date: 2026-08-02 10:44:26.597793
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '44b9875a2233'
down_revision: str | None = 'b89c8ebf3c3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)

    op.create_table('import_row_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mapped_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_row_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_row_results_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_row_results_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_row_results_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_row_results_status'), ['status'], unique=False)

    op.create_table('mapping_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_mapping_profile_client_name')
    )
    with op.batch_alter_table('mapping_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapping_profiles_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packaging', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'{}'")))
        batch_op.add_column(sa.Column('data_source', sa.String(length=40), nullable=False, server_default='manual'))
        batch_op.add_column(sa.Column('service_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ruleset_version', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('reference_data_version', sa.String(length=40), nullable=True))

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rows_success', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rows_error', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_column('rows_error')
        batch_op.drop_column('rows_success')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('reference_data_version')
        batch_op.drop_column('ruleset_version')
        batch_op.drop_column('service_comment')
        batch_op.drop_column('data_source')
        batch_op.drop_column('packaging')

    with op.batch_alter_table('mapping_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapping_profiles_client_id'))

    op.drop_table('mapping_profiles')
    with op.batch_alter_table('import_row_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_row_results_status'))
        batch_op.drop_index(batch_op.f('ix_import_row_results_job_id'))
        batch_op.drop_index(batch_op.f('ix_import_row_results_client_id'))
        batch_op.drop_index(batch_op.f('ix_import_row_results_card_id'))

    op.drop_table('import_row_results')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_client_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
